#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetworkVendite
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SocialNetworkVenditeDb")]
	public partial class SocialNetworkVenditeDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAMICIZIE(AMICIZIE instance);
    partial void UpdateAMICIZIE(AMICIZIE instance);
    partial void DeleteAMICIZIE(AMICIZIE instance);
    partial void InsertASSOCIAZIONI(ASSOCIAZIONI instance);
    partial void UpdateASSOCIAZIONI(ASSOCIAZIONI instance);
    partial void DeleteASSOCIAZIONI(ASSOCIAZIONI instance);
    partial void InsertCATEGORIE(CATEGORIE instance);
    partial void UpdateCATEGORIE(CATEGORIE instance);
    partial void DeleteCATEGORIE(CATEGORIE instance);
    partial void InsertSEZIONI(SEZIONI instance);
    partial void UpdateSEZIONI(SEZIONI instance);
    partial void DeleteSEZIONI(SEZIONI instance);
    partial void InsertUTENTI(UTENTI instance);
    partial void UpdateUTENTI(UTENTI instance);
    partial void DeleteUTENTI(UTENTI instance);
    partial void InsertRICHIESTE_AMICIZIE(RICHIESTE_AMICIZIE instance);
    partial void UpdateRICHIESTE_AMICIZIE(RICHIESTE_AMICIZIE instance);
    partial void DeleteRICHIESTE_AMICIZIE(RICHIESTE_AMICIZIE instance);
    partial void InsertMESSAGGI(MESSAGGI instance);
    partial void UpdateMESSAGGI(MESSAGGI instance);
    partial void DeleteMESSAGGI(MESSAGGI instance);
    partial void InsertPRODOTTI(PRODOTTI instance);
    partial void UpdatePRODOTTI(PRODOTTI instance);
    partial void DeletePRODOTTI(PRODOTTI instance);
    partial void InsertPOST(POST instance);
    partial void UpdatePOST(POST instance);
    partial void DeletePOST(POST instance);
    partial void InsertCOMMENTI(COMMENTI instance);
    partial void UpdateCOMMENTI(COMMENTI instance);
    partial void DeleteCOMMENTI(COMMENTI instance);
    #endregion
		
		public SocialNetworkVenditeDbDataContext() : 
				base(global::SocialNetworkVendite.Properties.Settings.Default.SocialNetworkVenditeDbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SocialNetworkVenditeDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SocialNetworkVenditeDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SocialNetworkVenditeDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SocialNetworkVenditeDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AMICIZIE> AMICIZIEs
		{
			get
			{
				return this.GetTable<AMICIZIE>();
			}
		}
		
		public System.Data.Linq.Table<ASSOCIAZIONI> ASSOCIAZIONIs
		{
			get
			{
				return this.GetTable<ASSOCIAZIONI>();
			}
		}
		
		public System.Data.Linq.Table<CATEGORIE> CATEGORIEs
		{
			get
			{
				return this.GetTable<CATEGORIE>();
			}
		}
		
		public System.Data.Linq.Table<SEZIONI> SEZIONIs
		{
			get
			{
				return this.GetTable<SEZIONI>();
			}
		}
		
		public System.Data.Linq.Table<UTENTI> UTENTIs
		{
			get
			{
				return this.GetTable<UTENTI>();
			}
		}
		
		public System.Data.Linq.Table<RICHIESTE_AMICIZIE> RICHIESTE_AMICIZIEs
		{
			get
			{
				return this.GetTable<RICHIESTE_AMICIZIE>();
			}
		}
		
		public System.Data.Linq.Table<MESSAGGI> MESSAGGIs
		{
			get
			{
				return this.GetTable<MESSAGGI>();
			}
		}
		
		public System.Data.Linq.Table<PRODOTTI> PRODOTTIs
		{
			get
			{
				return this.GetTable<PRODOTTI>();
			}
		}
		
		public System.Data.Linq.Table<POST> POSTs
		{
			get
			{
				return this.GetTable<POST>();
			}
		}
		
		public System.Data.Linq.Table<COMMENTI> COMMENTIs
		{
			get
			{
				return this.GetTable<COMMENTI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AMICIZIE")]
	public partial class AMICIZIE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _dataInizio;
		
		private System.TimeSpan _timeInizio;
		
		private System.Nullable<System.DateTime> _dataFine;
		
		private System.Nullable<System.TimeSpan> _timeFine;
		
		private string _emailUtente1;
		
		private string _emailUtente2;
		
		private EntityRef<UTENTI> _UTENTI;
		
		private EntityRef<UTENTI> _UTENTI1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndataInizioChanging(System.DateTime value);
    partial void OndataInizioChanged();
    partial void OntimeInizioChanging(System.TimeSpan value);
    partial void OntimeInizioChanged();
    partial void OndataFineChanging(System.Nullable<System.DateTime> value);
    partial void OndataFineChanged();
    partial void OntimeFineChanging(System.Nullable<System.TimeSpan> value);
    partial void OntimeFineChanged();
    partial void OnemailUtente1Changing(string value);
    partial void OnemailUtente1Changed();
    partial void OnemailUtente2Changing(string value);
    partial void OnemailUtente2Changed();
    #endregion
		
		public AMICIZIE()
		{
			this._UTENTI = default(EntityRef<UTENTI>);
			this._UTENTI1 = default(EntityRef<UTENTI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataInizio", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime dataInizio
		{
			get
			{
				return this._dataInizio;
			}
			set
			{
				if ((this._dataInizio != value))
				{
					this.OndataInizioChanging(value);
					this.SendPropertyChanging();
					this._dataInizio = value;
					this.SendPropertyChanged("dataInizio");
					this.OndataInizioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeInizio", DbType="Time NOT NULL", IsPrimaryKey=true)]
		public System.TimeSpan timeInizio
		{
			get
			{
				return this._timeInizio;
			}
			set
			{
				if ((this._timeInizio != value))
				{
					this.OntimeInizioChanging(value);
					this.SendPropertyChanging();
					this._timeInizio = value;
					this.SendPropertyChanged("timeInizio");
					this.OntimeInizioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataFine", DbType="Date")]
		public System.Nullable<System.DateTime> dataFine
		{
			get
			{
				return this._dataFine;
			}
			set
			{
				if ((this._dataFine != value))
				{
					this.OndataFineChanging(value);
					this.SendPropertyChanging();
					this._dataFine = value;
					this.SendPropertyChanged("dataFine");
					this.OndataFineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeFine", DbType="Time")]
		public System.Nullable<System.TimeSpan> timeFine
		{
			get
			{
				return this._timeFine;
			}
			set
			{
				if ((this._timeFine != value))
				{
					this.OntimeFineChanging(value);
					this.SendPropertyChanging();
					this._timeFine = value;
					this.SendPropertyChanged("timeFine");
					this.OntimeFineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailUtente1", DbType="VarChar(45) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string emailUtente1
		{
			get
			{
				return this._emailUtente1;
			}
			set
			{
				if ((this._emailUtente1 != value))
				{
					if (this._UTENTI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailUtente1Changing(value);
					this.SendPropertyChanging();
					this._emailUtente1 = value;
					this.SendPropertyChanged("emailUtente1");
					this.OnemailUtente1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailUtente2", DbType="VarChar(45) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string emailUtente2
		{
			get
			{
				return this._emailUtente2;
			}
			set
			{
				if ((this._emailUtente2 != value))
				{
					if (this._UTENTI1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailUtente2Changing(value);
					this.SendPropertyChanging();
					this._emailUtente2 = value;
					this.SendPropertyChanged("emailUtente2");
					this.OnemailUtente2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_AMICIZIE", Storage="_UTENTI", ThisKey="emailUtente1", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI
		{
			get
			{
				return this._UTENTI.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI.Entity = null;
						previousValue.AMICIZIEs.Remove(this);
					}
					this._UTENTI.Entity = value;
					if ((value != null))
					{
						value.AMICIZIEs.Add(this);
						this._emailUtente1 = value.email;
					}
					else
					{
						this._emailUtente1 = default(string);
					}
					this.SendPropertyChanged("UTENTI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_AMICIZIE1", Storage="_UTENTI1", ThisKey="emailUtente2", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI1
		{
			get
			{
				return this._UTENTI1.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI1.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI1.Entity = null;
						previousValue.AMICIZIEs1.Remove(this);
					}
					this._UTENTI1.Entity = value;
					if ((value != null))
					{
						value.AMICIZIEs1.Add(this);
						this._emailUtente2 = value.email;
					}
					else
					{
						this._emailUtente2 = default(string);
					}
					this.SendPropertyChanged("UTENTI1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ASSOCIAZIONI")]
	public partial class ASSOCIAZIONI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nomeSezione;
		
		private string _nomeCategoria;
		
		private EntityRef<CATEGORIE> _CATEGORIE;
		
		private EntityRef<SEZIONI> _SEZIONI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnomeSezioneChanging(string value);
    partial void OnnomeSezioneChanged();
    partial void OnnomeCategoriaChanging(string value);
    partial void OnnomeCategoriaChanged();
    #endregion
		
		public ASSOCIAZIONI()
		{
			this._CATEGORIE = default(EntityRef<CATEGORIE>);
			this._SEZIONI = default(EntityRef<SEZIONI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeSezione", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nomeSezione
		{
			get
			{
				return this._nomeSezione;
			}
			set
			{
				if ((this._nomeSezione != value))
				{
					if (this._SEZIONI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnomeSezioneChanging(value);
					this.SendPropertyChanging();
					this._nomeSezione = value;
					this.SendPropertyChanged("nomeSezione");
					this.OnnomeSezioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeCategoria", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nomeCategoria
		{
			get
			{
				return this._nomeCategoria;
			}
			set
			{
				if ((this._nomeCategoria != value))
				{
					if (this._CATEGORIE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnomeCategoriaChanging(value);
					this.SendPropertyChanging();
					this._nomeCategoria = value;
					this.SendPropertyChanged("nomeCategoria");
					this.OnnomeCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORIE_ASSOCIAZIONI", Storage="_CATEGORIE", ThisKey="nomeCategoria", OtherKey="nome", IsForeignKey=true)]
		public CATEGORIE CATEGORIE
		{
			get
			{
				return this._CATEGORIE.Entity;
			}
			set
			{
				CATEGORIE previousValue = this._CATEGORIE.Entity;
				if (((previousValue != value) 
							|| (this._CATEGORIE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CATEGORIE.Entity = null;
						previousValue.ASSOCIAZIONIs.Remove(this);
					}
					this._CATEGORIE.Entity = value;
					if ((value != null))
					{
						value.ASSOCIAZIONIs.Add(this);
						this._nomeCategoria = value.nome;
					}
					else
					{
						this._nomeCategoria = default(string);
					}
					this.SendPropertyChanged("CATEGORIE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEZIONI_ASSOCIAZIONI", Storage="_SEZIONI", ThisKey="nomeSezione", OtherKey="nome", IsForeignKey=true)]
		public SEZIONI SEZIONI
		{
			get
			{
				return this._SEZIONI.Entity;
			}
			set
			{
				SEZIONI previousValue = this._SEZIONI.Entity;
				if (((previousValue != value) 
							|| (this._SEZIONI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SEZIONI.Entity = null;
						previousValue.ASSOCIAZIONIs.Remove(this);
					}
					this._SEZIONI.Entity = value;
					if ((value != null))
					{
						value.ASSOCIAZIONIs.Add(this);
						this._nomeSezione = value.nome;
					}
					else
					{
						this._nomeSezione = default(string);
					}
					this.SendPropertyChanged("SEZIONI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CATEGORIE")]
	public partial class CATEGORIE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nome;
		
		private string _descrizione;
		
		private string _emailUtente;
		
		private EntitySet<ASSOCIAZIONI> _ASSOCIAZIONIs;
		
		private EntitySet<PRODOTTI> _PRODOTTIs;
		
		private EntityRef<UTENTI> _UTENTI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndescrizioneChanging(string value);
    partial void OndescrizioneChanged();
    partial void OnemailUtenteChanging(string value);
    partial void OnemailUtenteChanged();
    #endregion
		
		public CATEGORIE()
		{
			this._ASSOCIAZIONIs = new EntitySet<ASSOCIAZIONI>(new Action<ASSOCIAZIONI>(this.attach_ASSOCIAZIONIs), new Action<ASSOCIAZIONI>(this.detach_ASSOCIAZIONIs));
			this._PRODOTTIs = new EntitySet<PRODOTTI>(new Action<PRODOTTI>(this.attach_PRODOTTIs), new Action<PRODOTTI>(this.detach_PRODOTTIs));
			this._UTENTI = default(EntityRef<UTENTI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrizione", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				if ((this._descrizione != value))
				{
					this.OndescrizioneChanging(value);
					this.SendPropertyChanging();
					this._descrizione = value;
					this.SendPropertyChanged("descrizione");
					this.OndescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailUtente", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string emailUtente
		{
			get
			{
				return this._emailUtente;
			}
			set
			{
				if ((this._emailUtente != value))
				{
					if (this._UTENTI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailUtenteChanging(value);
					this.SendPropertyChanging();
					this._emailUtente = value;
					this.SendPropertyChanged("emailUtente");
					this.OnemailUtenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORIE_ASSOCIAZIONI", Storage="_ASSOCIAZIONIs", ThisKey="nome", OtherKey="nomeCategoria")]
		public EntitySet<ASSOCIAZIONI> ASSOCIAZIONIs
		{
			get
			{
				return this._ASSOCIAZIONIs;
			}
			set
			{
				this._ASSOCIAZIONIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORIE_PRODOTTI", Storage="_PRODOTTIs", ThisKey="nome", OtherKey="nomeCategoria")]
		public EntitySet<PRODOTTI> PRODOTTIs
		{
			get
			{
				return this._PRODOTTIs;
			}
			set
			{
				this._PRODOTTIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_CATEGORIE", Storage="_UTENTI", ThisKey="emailUtente", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI
		{
			get
			{
				return this._UTENTI.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI.Entity = null;
						previousValue.CATEGORIEs.Remove(this);
					}
					this._UTENTI.Entity = value;
					if ((value != null))
					{
						value.CATEGORIEs.Add(this);
						this._emailUtente = value.email;
					}
					else
					{
						this._emailUtente = default(string);
					}
					this.SendPropertyChanged("UTENTI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ASSOCIAZIONIs(ASSOCIAZIONI entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIE = this;
		}
		
		private void detach_ASSOCIAZIONIs(ASSOCIAZIONI entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIE = null;
		}
		
		private void attach_PRODOTTIs(PRODOTTI entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIE = this;
		}
		
		private void detach_PRODOTTIs(PRODOTTI entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SEZIONI")]
	public partial class SEZIONI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nome;
		
		private string _descrizione;
		
		private System.Data.Linq.Binary _immagine;
		
		private System.DateTime _dataCreazione;
		
		private string _emailUtente;
		
		private EntitySet<ASSOCIAZIONI> _ASSOCIAZIONIs;
		
		private EntitySet<PRODOTTI> _PRODOTTIs;
		
		private EntitySet<POST> _POSTs;
		
		private EntityRef<UTENTI> _UTENTI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndescrizioneChanging(string value);
    partial void OndescrizioneChanged();
    partial void OnimmagineChanging(System.Data.Linq.Binary value);
    partial void OnimmagineChanged();
    partial void OndataCreazioneChanging(System.DateTime value);
    partial void OndataCreazioneChanged();
    partial void OnemailUtenteChanging(string value);
    partial void OnemailUtenteChanged();
    #endregion
		
		public SEZIONI()
		{
			this._ASSOCIAZIONIs = new EntitySet<ASSOCIAZIONI>(new Action<ASSOCIAZIONI>(this.attach_ASSOCIAZIONIs), new Action<ASSOCIAZIONI>(this.detach_ASSOCIAZIONIs));
			this._PRODOTTIs = new EntitySet<PRODOTTI>(new Action<PRODOTTI>(this.attach_PRODOTTIs), new Action<PRODOTTI>(this.detach_PRODOTTIs));
			this._POSTs = new EntitySet<POST>(new Action<POST>(this.attach_POSTs), new Action<POST>(this.detach_POSTs));
			this._UTENTI = default(EntityRef<UTENTI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrizione", DbType="VarChar(400) NOT NULL", CanBeNull=false)]
		public string descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				if ((this._descrizione != value))
				{
					this.OndescrizioneChanging(value);
					this.SendPropertyChanging();
					this._descrizione = value;
					this.SendPropertyChanged("descrizione");
					this.OndescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_immagine", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary immagine
		{
			get
			{
				return this._immagine;
			}
			set
			{
				if ((this._immagine != value))
				{
					this.OnimmagineChanging(value);
					this.SendPropertyChanging();
					this._immagine = value;
					this.SendPropertyChanged("immagine");
					this.OnimmagineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCreazione", DbType="Date NOT NULL")]
		public System.DateTime dataCreazione
		{
			get
			{
				return this._dataCreazione;
			}
			set
			{
				if ((this._dataCreazione != value))
				{
					this.OndataCreazioneChanging(value);
					this.SendPropertyChanging();
					this._dataCreazione = value;
					this.SendPropertyChanged("dataCreazione");
					this.OndataCreazioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailUtente", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string emailUtente
		{
			get
			{
				return this._emailUtente;
			}
			set
			{
				if ((this._emailUtente != value))
				{
					if (this._UTENTI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailUtenteChanging(value);
					this.SendPropertyChanging();
					this._emailUtente = value;
					this.SendPropertyChanged("emailUtente");
					this.OnemailUtenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEZIONI_ASSOCIAZIONI", Storage="_ASSOCIAZIONIs", ThisKey="nome", OtherKey="nomeSezione")]
		public EntitySet<ASSOCIAZIONI> ASSOCIAZIONIs
		{
			get
			{
				return this._ASSOCIAZIONIs;
			}
			set
			{
				this._ASSOCIAZIONIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEZIONI_PRODOTTI", Storage="_PRODOTTIs", ThisKey="nome", OtherKey="nomeSezione")]
		public EntitySet<PRODOTTI> PRODOTTIs
		{
			get
			{
				return this._PRODOTTIs;
			}
			set
			{
				this._PRODOTTIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEZIONI_POST", Storage="_POSTs", ThisKey="nome", OtherKey="nomeSezione")]
		public EntitySet<POST> POSTs
		{
			get
			{
				return this._POSTs;
			}
			set
			{
				this._POSTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_SEZIONI", Storage="_UTENTI", ThisKey="emailUtente", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI
		{
			get
			{
				return this._UTENTI.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI.Entity = null;
						previousValue.SEZIONIs.Remove(this);
					}
					this._UTENTI.Entity = value;
					if ((value != null))
					{
						value.SEZIONIs.Add(this);
						this._emailUtente = value.email;
					}
					else
					{
						this._emailUtente = default(string);
					}
					this.SendPropertyChanged("UTENTI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ASSOCIAZIONIs(ASSOCIAZIONI entity)
		{
			this.SendPropertyChanging();
			entity.SEZIONI = this;
		}
		
		private void detach_ASSOCIAZIONIs(ASSOCIAZIONI entity)
		{
			this.SendPropertyChanging();
			entity.SEZIONI = null;
		}
		
		private void attach_PRODOTTIs(PRODOTTI entity)
		{
			this.SendPropertyChanging();
			entity.SEZIONI = this;
		}
		
		private void detach_PRODOTTIs(PRODOTTI entity)
		{
			this.SendPropertyChanging();
			entity.SEZIONI = null;
		}
		
		private void attach_POSTs(POST entity)
		{
			this.SendPropertyChanging();
			entity.SEZIONI = this;
		}
		
		private void detach_POSTs(POST entity)
		{
			this.SendPropertyChanging();
			entity.SEZIONI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UTENTI")]
	public partial class UTENTI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _email;
		
		private string _password;
		
		private string _nome;
		
		private string _cognome;
		
		private string _sesso;
		
		private System.DateTime _dataNascita;
		
		private string _luogoNascita;
		
		private string _viaResidenza;
		
		private short _numeroCivicoResidenza;
		
		private string _cittaResidenza;
		
		private string _numeroTelefono;
		
		private System.Data.Linq.Binary _immagine;
		
		private bool _amministratore;
		
		private EntitySet<AMICIZIE> _AMICIZIEs;
		
		private EntitySet<AMICIZIE> _AMICIZIEs1;
		
		private EntitySet<CATEGORIE> _CATEGORIEs;
		
		private EntitySet<SEZIONI> _SEZIONIs;
		
		private EntitySet<RICHIESTE_AMICIZIE> _RICHIESTE_AMICIZIEs;
		
		private EntitySet<RICHIESTE_AMICIZIE> _RICHIESTE_AMICIZIEs1;
		
		private EntitySet<MESSAGGI> _MESSAGGIs;
		
		private EntitySet<MESSAGGI> _MESSAGGIs1;
		
		private EntitySet<PRODOTTI> _PRODOTTIs;
		
		private EntitySet<PRODOTTI> _PRODOTTIs1;
		
		private EntitySet<POST> _POSTs;
		
		private EntitySet<COMMENTI> _COMMENTIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OncognomeChanging(string value);
    partial void OncognomeChanged();
    partial void OnsessoChanging(string value);
    partial void OnsessoChanged();
    partial void OndataNascitaChanging(System.DateTime value);
    partial void OndataNascitaChanged();
    partial void OnluogoNascitaChanging(string value);
    partial void OnluogoNascitaChanged();
    partial void OnviaResidenzaChanging(string value);
    partial void OnviaResidenzaChanged();
    partial void OnnumeroCivicoResidenzaChanging(short value);
    partial void OnnumeroCivicoResidenzaChanged();
    partial void OncittaResidenzaChanging(string value);
    partial void OncittaResidenzaChanged();
    partial void OnnumeroTelefonoChanging(string value);
    partial void OnnumeroTelefonoChanged();
    partial void OnimmagineChanging(System.Data.Linq.Binary value);
    partial void OnimmagineChanged();
    partial void OnamministratoreChanging(bool value);
    partial void OnamministratoreChanged();
    #endregion
		
		public UTENTI()
		{
			this._AMICIZIEs = new EntitySet<AMICIZIE>(new Action<AMICIZIE>(this.attach_AMICIZIEs), new Action<AMICIZIE>(this.detach_AMICIZIEs));
			this._AMICIZIEs1 = new EntitySet<AMICIZIE>(new Action<AMICIZIE>(this.attach_AMICIZIEs1), new Action<AMICIZIE>(this.detach_AMICIZIEs1));
			this._CATEGORIEs = new EntitySet<CATEGORIE>(new Action<CATEGORIE>(this.attach_CATEGORIEs), new Action<CATEGORIE>(this.detach_CATEGORIEs));
			this._SEZIONIs = new EntitySet<SEZIONI>(new Action<SEZIONI>(this.attach_SEZIONIs), new Action<SEZIONI>(this.detach_SEZIONIs));
			this._RICHIESTE_AMICIZIEs = new EntitySet<RICHIESTE_AMICIZIE>(new Action<RICHIESTE_AMICIZIE>(this.attach_RICHIESTE_AMICIZIEs), new Action<RICHIESTE_AMICIZIE>(this.detach_RICHIESTE_AMICIZIEs));
			this._RICHIESTE_AMICIZIEs1 = new EntitySet<RICHIESTE_AMICIZIE>(new Action<RICHIESTE_AMICIZIE>(this.attach_RICHIESTE_AMICIZIEs1), new Action<RICHIESTE_AMICIZIE>(this.detach_RICHIESTE_AMICIZIEs1));
			this._MESSAGGIs = new EntitySet<MESSAGGI>(new Action<MESSAGGI>(this.attach_MESSAGGIs), new Action<MESSAGGI>(this.detach_MESSAGGIs));
			this._MESSAGGIs1 = new EntitySet<MESSAGGI>(new Action<MESSAGGI>(this.attach_MESSAGGIs1), new Action<MESSAGGI>(this.detach_MESSAGGIs1));
			this._PRODOTTIs = new EntitySet<PRODOTTI>(new Action<PRODOTTI>(this.attach_PRODOTTIs), new Action<PRODOTTI>(this.detach_PRODOTTIs));
			this._PRODOTTIs1 = new EntitySet<PRODOTTI>(new Action<PRODOTTI>(this.attach_PRODOTTIs1), new Action<PRODOTTI>(this.detach_PRODOTTIs1));
			this._POSTs = new EntitySet<POST>(new Action<POST>(this.attach_POSTs), new Action<POST>(this.detach_POSTs));
			this._COMMENTIs = new EntitySet<COMMENTI>(new Action<COMMENTI>(this.attach_COMMENTIs), new Action<COMMENTI>(this.detach_COMMENTIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(45) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cognome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cognome
		{
			get
			{
				return this._cognome;
			}
			set
			{
				if ((this._cognome != value))
				{
					this.OncognomeChanging(value);
					this.SendPropertyChanging();
					this._cognome = value;
					this.SendPropertyChanged("cognome");
					this.OncognomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sesso", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string sesso
		{
			get
			{
				return this._sesso;
			}
			set
			{
				if ((this._sesso != value))
				{
					this.OnsessoChanging(value);
					this.SendPropertyChanging();
					this._sesso = value;
					this.SendPropertyChanged("sesso");
					this.OnsessoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataNascita", DbType="Date NOT NULL")]
		public System.DateTime dataNascita
		{
			get
			{
				return this._dataNascita;
			}
			set
			{
				if ((this._dataNascita != value))
				{
					this.OndataNascitaChanging(value);
					this.SendPropertyChanging();
					this._dataNascita = value;
					this.SendPropertyChanged("dataNascita");
					this.OndataNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luogoNascita", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string luogoNascita
		{
			get
			{
				return this._luogoNascita;
			}
			set
			{
				if ((this._luogoNascita != value))
				{
					this.OnluogoNascitaChanging(value);
					this.SendPropertyChanging();
					this._luogoNascita = value;
					this.SendPropertyChanged("luogoNascita");
					this.OnluogoNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viaResidenza", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string viaResidenza
		{
			get
			{
				return this._viaResidenza;
			}
			set
			{
				if ((this._viaResidenza != value))
				{
					this.OnviaResidenzaChanging(value);
					this.SendPropertyChanging();
					this._viaResidenza = value;
					this.SendPropertyChanged("viaResidenza");
					this.OnviaResidenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroCivicoResidenza", DbType="SmallInt NOT NULL")]
		public short numeroCivicoResidenza
		{
			get
			{
				return this._numeroCivicoResidenza;
			}
			set
			{
				if ((this._numeroCivicoResidenza != value))
				{
					this.OnnumeroCivicoResidenzaChanging(value);
					this.SendPropertyChanging();
					this._numeroCivicoResidenza = value;
					this.SendPropertyChanged("numeroCivicoResidenza");
					this.OnnumeroCivicoResidenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cittaResidenza", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string cittaResidenza
		{
			get
			{
				return this._cittaResidenza;
			}
			set
			{
				if ((this._cittaResidenza != value))
				{
					this.OncittaResidenzaChanging(value);
					this.SendPropertyChanging();
					this._cittaResidenza = value;
					this.SendPropertyChanged("cittaResidenza");
					this.OncittaResidenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroTelefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string numeroTelefono
		{
			get
			{
				return this._numeroTelefono;
			}
			set
			{
				if ((this._numeroTelefono != value))
				{
					this.OnnumeroTelefonoChanging(value);
					this.SendPropertyChanging();
					this._numeroTelefono = value;
					this.SendPropertyChanged("numeroTelefono");
					this.OnnumeroTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_immagine", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary immagine
		{
			get
			{
				return this._immagine;
			}
			set
			{
				if ((this._immagine != value))
				{
					this.OnimmagineChanging(value);
					this.SendPropertyChanging();
					this._immagine = value;
					this.SendPropertyChanged("immagine");
					this.OnimmagineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amministratore", DbType="Bit NOT NULL")]
		public bool amministratore
		{
			get
			{
				return this._amministratore;
			}
			set
			{
				if ((this._amministratore != value))
				{
					this.OnamministratoreChanging(value);
					this.SendPropertyChanging();
					this._amministratore = value;
					this.SendPropertyChanged("amministratore");
					this.OnamministratoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_AMICIZIE", Storage="_AMICIZIEs", ThisKey="email", OtherKey="emailUtente1")]
		public EntitySet<AMICIZIE> AMICIZIEs
		{
			get
			{
				return this._AMICIZIEs;
			}
			set
			{
				this._AMICIZIEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_AMICIZIE1", Storage="_AMICIZIEs1", ThisKey="email", OtherKey="emailUtente2")]
		public EntitySet<AMICIZIE> AMICIZIEs1
		{
			get
			{
				return this._AMICIZIEs1;
			}
			set
			{
				this._AMICIZIEs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_CATEGORIE", Storage="_CATEGORIEs", ThisKey="email", OtherKey="emailUtente")]
		public EntitySet<CATEGORIE> CATEGORIEs
		{
			get
			{
				return this._CATEGORIEs;
			}
			set
			{
				this._CATEGORIEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_SEZIONI", Storage="_SEZIONIs", ThisKey="email", OtherKey="emailUtente")]
		public EntitySet<SEZIONI> SEZIONIs
		{
			get
			{
				return this._SEZIONIs;
			}
			set
			{
				this._SEZIONIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_RICHIESTE_AMICIZIE", Storage="_RICHIESTE_AMICIZIEs", ThisKey="email", OtherKey="emailMittente")]
		public EntitySet<RICHIESTE_AMICIZIE> RICHIESTE_AMICIZIEs
		{
			get
			{
				return this._RICHIESTE_AMICIZIEs;
			}
			set
			{
				this._RICHIESTE_AMICIZIEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_RICHIESTE_AMICIZIE1", Storage="_RICHIESTE_AMICIZIEs1", ThisKey="email", OtherKey="emailDestinatario")]
		public EntitySet<RICHIESTE_AMICIZIE> RICHIESTE_AMICIZIEs1
		{
			get
			{
				return this._RICHIESTE_AMICIZIEs1;
			}
			set
			{
				this._RICHIESTE_AMICIZIEs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_MESSAGGI", Storage="_MESSAGGIs", ThisKey="email", OtherKey="emailMittente")]
		public EntitySet<MESSAGGI> MESSAGGIs
		{
			get
			{
				return this._MESSAGGIs;
			}
			set
			{
				this._MESSAGGIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_MESSAGGI1", Storage="_MESSAGGIs1", ThisKey="email", OtherKey="emailDestinatario")]
		public EntitySet<MESSAGGI> MESSAGGIs1
		{
			get
			{
				return this._MESSAGGIs1;
			}
			set
			{
				this._MESSAGGIs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_PRODOTTI", Storage="_PRODOTTIs", ThisKey="email", OtherKey="emailUtenteAcquisto")]
		public EntitySet<PRODOTTI> PRODOTTIs
		{
			get
			{
				return this._PRODOTTIs;
			}
			set
			{
				this._PRODOTTIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_PRODOTTI1", Storage="_PRODOTTIs1", ThisKey="email", OtherKey="emailUtenteVendita")]
		public EntitySet<PRODOTTI> PRODOTTIs1
		{
			get
			{
				return this._PRODOTTIs1;
			}
			set
			{
				this._PRODOTTIs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_POST", Storage="_POSTs", ThisKey="email", OtherKey="emailUtente")]
		public EntitySet<POST> POSTs
		{
			get
			{
				return this._POSTs;
			}
			set
			{
				this._POSTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_COMMENTI", Storage="_COMMENTIs", ThisKey="email", OtherKey="emailUtente")]
		public EntitySet<COMMENTI> COMMENTIs
		{
			get
			{
				return this._COMMENTIs;
			}
			set
			{
				this._COMMENTIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AMICIZIEs(AMICIZIE entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = this;
		}
		
		private void detach_AMICIZIEs(AMICIZIE entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = null;
		}
		
		private void attach_AMICIZIEs1(AMICIZIE entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI1 = this;
		}
		
		private void detach_AMICIZIEs1(AMICIZIE entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI1 = null;
		}
		
		private void attach_CATEGORIEs(CATEGORIE entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = this;
		}
		
		private void detach_CATEGORIEs(CATEGORIE entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = null;
		}
		
		private void attach_SEZIONIs(SEZIONI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = this;
		}
		
		private void detach_SEZIONIs(SEZIONI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = null;
		}
		
		private void attach_RICHIESTE_AMICIZIEs(RICHIESTE_AMICIZIE entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = this;
		}
		
		private void detach_RICHIESTE_AMICIZIEs(RICHIESTE_AMICIZIE entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = null;
		}
		
		private void attach_RICHIESTE_AMICIZIEs1(RICHIESTE_AMICIZIE entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI1 = this;
		}
		
		private void detach_RICHIESTE_AMICIZIEs1(RICHIESTE_AMICIZIE entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI1 = null;
		}
		
		private void attach_MESSAGGIs(MESSAGGI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = this;
		}
		
		private void detach_MESSAGGIs(MESSAGGI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = null;
		}
		
		private void attach_MESSAGGIs1(MESSAGGI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI1 = this;
		}
		
		private void detach_MESSAGGIs1(MESSAGGI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI1 = null;
		}
		
		private void attach_PRODOTTIs(PRODOTTI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = this;
		}
		
		private void detach_PRODOTTIs(PRODOTTI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = null;
		}
		
		private void attach_PRODOTTIs1(PRODOTTI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI1 = this;
		}
		
		private void detach_PRODOTTIs1(PRODOTTI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI1 = null;
		}
		
		private void attach_POSTs(POST entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = this;
		}
		
		private void detach_POSTs(POST entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = null;
		}
		
		private void attach_COMMENTIs(COMMENTI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = this;
		}
		
		private void detach_COMMENTIs(COMMENTI entity)
		{
			this.SendPropertyChanging();
			entity.UTENTI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RICHIESTE_AMICIZIE")]
	public partial class RICHIESTE_AMICIZIE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _dataRichiesta;
		
		private System.TimeSpan _timeRichiesta;
		
		private System.Nullable<System.DateTime> _dataRisposta;
		
		private System.Nullable<System.TimeSpan> _timeRisposta;
		
		private System.Nullable<bool> _accettata;
		
		private string _emailMittente;
		
		private string _emailDestinatario;
		
		private EntityRef<UTENTI> _UTENTI;
		
		private EntityRef<UTENTI> _UTENTI1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndataRichiestaChanging(System.DateTime value);
    partial void OndataRichiestaChanged();
    partial void OntimeRichiestaChanging(System.TimeSpan value);
    partial void OntimeRichiestaChanged();
    partial void OndataRispostaChanging(System.Nullable<System.DateTime> value);
    partial void OndataRispostaChanged();
    partial void OntimeRispostaChanging(System.Nullable<System.TimeSpan> value);
    partial void OntimeRispostaChanged();
    partial void OnaccettataChanging(System.Nullable<bool> value);
    partial void OnaccettataChanged();
    partial void OnemailMittenteChanging(string value);
    partial void OnemailMittenteChanged();
    partial void OnemailDestinatarioChanging(string value);
    partial void OnemailDestinatarioChanged();
    #endregion
		
		public RICHIESTE_AMICIZIE()
		{
			this._UTENTI = default(EntityRef<UTENTI>);
			this._UTENTI1 = default(EntityRef<UTENTI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataRichiesta", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime dataRichiesta
		{
			get
			{
				return this._dataRichiesta;
			}
			set
			{
				if ((this._dataRichiesta != value))
				{
					this.OndataRichiestaChanging(value);
					this.SendPropertyChanging();
					this._dataRichiesta = value;
					this.SendPropertyChanged("dataRichiesta");
					this.OndataRichiestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeRichiesta", DbType="Time NOT NULL", IsPrimaryKey=true)]
		public System.TimeSpan timeRichiesta
		{
			get
			{
				return this._timeRichiesta;
			}
			set
			{
				if ((this._timeRichiesta != value))
				{
					this.OntimeRichiestaChanging(value);
					this.SendPropertyChanging();
					this._timeRichiesta = value;
					this.SendPropertyChanged("timeRichiesta");
					this.OntimeRichiestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataRisposta", DbType="Date")]
		public System.Nullable<System.DateTime> dataRisposta
		{
			get
			{
				return this._dataRisposta;
			}
			set
			{
				if ((this._dataRisposta != value))
				{
					this.OndataRispostaChanging(value);
					this.SendPropertyChanging();
					this._dataRisposta = value;
					this.SendPropertyChanged("dataRisposta");
					this.OndataRispostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeRisposta", DbType="Time")]
		public System.Nullable<System.TimeSpan> timeRisposta
		{
			get
			{
				return this._timeRisposta;
			}
			set
			{
				if ((this._timeRisposta != value))
				{
					this.OntimeRispostaChanging(value);
					this.SendPropertyChanging();
					this._timeRisposta = value;
					this.SendPropertyChanged("timeRisposta");
					this.OntimeRispostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accettata", DbType="Bit")]
		public System.Nullable<bool> accettata
		{
			get
			{
				return this._accettata;
			}
			set
			{
				if ((this._accettata != value))
				{
					this.OnaccettataChanging(value);
					this.SendPropertyChanging();
					this._accettata = value;
					this.SendPropertyChanged("accettata");
					this.OnaccettataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailMittente", DbType="VarChar(45) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string emailMittente
		{
			get
			{
				return this._emailMittente;
			}
			set
			{
				if ((this._emailMittente != value))
				{
					if (this._UTENTI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailMittenteChanging(value);
					this.SendPropertyChanging();
					this._emailMittente = value;
					this.SendPropertyChanged("emailMittente");
					this.OnemailMittenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailDestinatario", DbType="VarChar(45) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string emailDestinatario
		{
			get
			{
				return this._emailDestinatario;
			}
			set
			{
				if ((this._emailDestinatario != value))
				{
					if (this._UTENTI1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailDestinatarioChanging(value);
					this.SendPropertyChanging();
					this._emailDestinatario = value;
					this.SendPropertyChanged("emailDestinatario");
					this.OnemailDestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_RICHIESTE_AMICIZIE", Storage="_UTENTI", ThisKey="emailMittente", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI
		{
			get
			{
				return this._UTENTI.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI.Entity = null;
						previousValue.RICHIESTE_AMICIZIEs.Remove(this);
					}
					this._UTENTI.Entity = value;
					if ((value != null))
					{
						value.RICHIESTE_AMICIZIEs.Add(this);
						this._emailMittente = value.email;
					}
					else
					{
						this._emailMittente = default(string);
					}
					this.SendPropertyChanged("UTENTI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_RICHIESTE_AMICIZIE1", Storage="_UTENTI1", ThisKey="emailDestinatario", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI1
		{
			get
			{
				return this._UTENTI1.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI1.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI1.Entity = null;
						previousValue.RICHIESTE_AMICIZIEs1.Remove(this);
					}
					this._UTENTI1.Entity = value;
					if ((value != null))
					{
						value.RICHIESTE_AMICIZIEs1.Add(this);
						this._emailDestinatario = value.email;
					}
					else
					{
						this._emailDestinatario = default(string);
					}
					this.SendPropertyChanged("UTENTI1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MESSAGGI")]
	public partial class MESSAGGI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _codiceMessaggio;
		
		private System.DateTime _data;
		
		private System.TimeSpan _time;
		
		private string _descrizione;
		
		private string _emailMittente;
		
		private string _emailDestinatario;
		
		private EntityRef<UTENTI> _UTENTI;
		
		private EntityRef<UTENTI> _UTENTI1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodiceMessaggioChanging(long value);
    partial void OncodiceMessaggioChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    partial void OntimeChanging(System.TimeSpan value);
    partial void OntimeChanged();
    partial void OndescrizioneChanging(string value);
    partial void OndescrizioneChanged();
    partial void OnemailMittenteChanging(string value);
    partial void OnemailMittenteChanged();
    partial void OnemailDestinatarioChanging(string value);
    partial void OnemailDestinatarioChanged();
    #endregion
		
		public MESSAGGI()
		{
			this._UTENTI = default(EntityRef<UTENTI>);
			this._UTENTI1 = default(EntityRef<UTENTI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codiceMessaggio", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long codiceMessaggio
		{
			get
			{
				return this._codiceMessaggio;
			}
			set
			{
				if ((this._codiceMessaggio != value))
				{
					this.OncodiceMessaggioChanging(value);
					this.SendPropertyChanging();
					this._codiceMessaggio = value;
					this.SendPropertyChanged("codiceMessaggio");
					this.OncodiceMessaggioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="Date NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time NOT NULL")]
		public System.TimeSpan time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrizione", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				if ((this._descrizione != value))
				{
					this.OndescrizioneChanging(value);
					this.SendPropertyChanging();
					this._descrizione = value;
					this.SendPropertyChanged("descrizione");
					this.OndescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailMittente", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string emailMittente
		{
			get
			{
				return this._emailMittente;
			}
			set
			{
				if ((this._emailMittente != value))
				{
					if (this._UTENTI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailMittenteChanging(value);
					this.SendPropertyChanging();
					this._emailMittente = value;
					this.SendPropertyChanged("emailMittente");
					this.OnemailMittenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailDestinatario", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string emailDestinatario
		{
			get
			{
				return this._emailDestinatario;
			}
			set
			{
				if ((this._emailDestinatario != value))
				{
					if (this._UTENTI1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailDestinatarioChanging(value);
					this.SendPropertyChanging();
					this._emailDestinatario = value;
					this.SendPropertyChanged("emailDestinatario");
					this.OnemailDestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_MESSAGGI", Storage="_UTENTI", ThisKey="emailMittente", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI
		{
			get
			{
				return this._UTENTI.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI.Entity = null;
						previousValue.MESSAGGIs.Remove(this);
					}
					this._UTENTI.Entity = value;
					if ((value != null))
					{
						value.MESSAGGIs.Add(this);
						this._emailMittente = value.email;
					}
					else
					{
						this._emailMittente = default(string);
					}
					this.SendPropertyChanged("UTENTI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_MESSAGGI1", Storage="_UTENTI1", ThisKey="emailDestinatario", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI1
		{
			get
			{
				return this._UTENTI1.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI1.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI1.Entity = null;
						previousValue.MESSAGGIs1.Remove(this);
					}
					this._UTENTI1.Entity = value;
					if ((value != null))
					{
						value.MESSAGGIs1.Add(this);
						this._emailDestinatario = value.email;
					}
					else
					{
						this._emailDestinatario = default(string);
					}
					this.SendPropertyChanged("UTENTI1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODOTTI")]
	public partial class PRODOTTI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _codiceProdotto;
		
		private string _descrizione;
		
		private System.Data.Linq.Binary _immagine;
		
		private int _prezzo;
		
		private System.Nullable<System.DateTime> _dataAcquisto;
		
		private string _emailUtenteAcquisto;
		
		private System.DateTime _dataVendita;
		
		private System.Nullable<bool> _venduto;
		
		private string _emailUtenteVendita;
		
		private string _nomeCategoria;
		
		private string _nomeSezione;
		
		private EntityRef<CATEGORIE> _CATEGORIE;
		
		private EntityRef<SEZIONI> _SEZIONI;
		
		private EntityRef<UTENTI> _UTENTI;
		
		private EntityRef<UTENTI> _UTENTI1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodiceProdottoChanging(long value);
    partial void OncodiceProdottoChanged();
    partial void OndescrizioneChanging(string value);
    partial void OndescrizioneChanged();
    partial void OnimmagineChanging(System.Data.Linq.Binary value);
    partial void OnimmagineChanged();
    partial void OnprezzoChanging(int value);
    partial void OnprezzoChanged();
    partial void OndataAcquistoChanging(System.Nullable<System.DateTime> value);
    partial void OndataAcquistoChanged();
    partial void OnemailUtenteAcquistoChanging(string value);
    partial void OnemailUtenteAcquistoChanged();
    partial void OndataVenditaChanging(System.DateTime value);
    partial void OndataVenditaChanged();
    partial void OnvendutoChanging(System.Nullable<bool> value);
    partial void OnvendutoChanged();
    partial void OnemailUtenteVenditaChanging(string value);
    partial void OnemailUtenteVenditaChanged();
    partial void OnnomeCategoriaChanging(string value);
    partial void OnnomeCategoriaChanged();
    partial void OnnomeSezioneChanging(string value);
    partial void OnnomeSezioneChanged();
    #endregion
		
		public PRODOTTI()
		{
			this._CATEGORIE = default(EntityRef<CATEGORIE>);
			this._SEZIONI = default(EntityRef<SEZIONI>);
			this._UTENTI = default(EntityRef<UTENTI>);
			this._UTENTI1 = default(EntityRef<UTENTI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codiceProdotto", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long codiceProdotto
		{
			get
			{
				return this._codiceProdotto;
			}
			set
			{
				if ((this._codiceProdotto != value))
				{
					this.OncodiceProdottoChanging(value);
					this.SendPropertyChanging();
					this._codiceProdotto = value;
					this.SendPropertyChanged("codiceProdotto");
					this.OncodiceProdottoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrizione", DbType="VarChar(500)")]
		public string descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				if ((this._descrizione != value))
				{
					this.OndescrizioneChanging(value);
					this.SendPropertyChanging();
					this._descrizione = value;
					this.SendPropertyChanged("descrizione");
					this.OndescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_immagine", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary immagine
		{
			get
			{
				return this._immagine;
			}
			set
			{
				if ((this._immagine != value))
				{
					this.OnimmagineChanging(value);
					this.SendPropertyChanging();
					this._immagine = value;
					this.SendPropertyChanged("immagine");
					this.OnimmagineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prezzo", DbType="Int NOT NULL")]
		public int prezzo
		{
			get
			{
				return this._prezzo;
			}
			set
			{
				if ((this._prezzo != value))
				{
					this.OnprezzoChanging(value);
					this.SendPropertyChanging();
					this._prezzo = value;
					this.SendPropertyChanged("prezzo");
					this.OnprezzoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataAcquisto", DbType="Date")]
		public System.Nullable<System.DateTime> dataAcquisto
		{
			get
			{
				return this._dataAcquisto;
			}
			set
			{
				if ((this._dataAcquisto != value))
				{
					this.OndataAcquistoChanging(value);
					this.SendPropertyChanging();
					this._dataAcquisto = value;
					this.SendPropertyChanged("dataAcquisto");
					this.OndataAcquistoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailUtenteAcquisto", DbType="VarChar(45)")]
		public string emailUtenteAcquisto
		{
			get
			{
				return this._emailUtenteAcquisto;
			}
			set
			{
				if ((this._emailUtenteAcquisto != value))
				{
					if (this._UTENTI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailUtenteAcquistoChanging(value);
					this.SendPropertyChanging();
					this._emailUtenteAcquisto = value;
					this.SendPropertyChanged("emailUtenteAcquisto");
					this.OnemailUtenteAcquistoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataVendita", DbType="Date NOT NULL")]
		public System.DateTime dataVendita
		{
			get
			{
				return this._dataVendita;
			}
			set
			{
				if ((this._dataVendita != value))
				{
					this.OndataVenditaChanging(value);
					this.SendPropertyChanging();
					this._dataVendita = value;
					this.SendPropertyChanged("dataVendita");
					this.OndataVenditaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_venduto", DbType="Bit")]
		public System.Nullable<bool> venduto
		{
			get
			{
				return this._venduto;
			}
			set
			{
				if ((this._venduto != value))
				{
					this.OnvendutoChanging(value);
					this.SendPropertyChanging();
					this._venduto = value;
					this.SendPropertyChanged("venduto");
					this.OnvendutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailUtenteVendita", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string emailUtenteVendita
		{
			get
			{
				return this._emailUtenteVendita;
			}
			set
			{
				if ((this._emailUtenteVendita != value))
				{
					if (this._UTENTI1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailUtenteVenditaChanging(value);
					this.SendPropertyChanging();
					this._emailUtenteVendita = value;
					this.SendPropertyChanged("emailUtenteVendita");
					this.OnemailUtenteVenditaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeCategoria", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nomeCategoria
		{
			get
			{
				return this._nomeCategoria;
			}
			set
			{
				if ((this._nomeCategoria != value))
				{
					if (this._CATEGORIE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnomeCategoriaChanging(value);
					this.SendPropertyChanging();
					this._nomeCategoria = value;
					this.SendPropertyChanged("nomeCategoria");
					this.OnnomeCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeSezione", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nomeSezione
		{
			get
			{
				return this._nomeSezione;
			}
			set
			{
				if ((this._nomeSezione != value))
				{
					if (this._SEZIONI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnomeSezioneChanging(value);
					this.SendPropertyChanging();
					this._nomeSezione = value;
					this.SendPropertyChanged("nomeSezione");
					this.OnnomeSezioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORIE_PRODOTTI", Storage="_CATEGORIE", ThisKey="nomeCategoria", OtherKey="nome", IsForeignKey=true)]
		public CATEGORIE CATEGORIE
		{
			get
			{
				return this._CATEGORIE.Entity;
			}
			set
			{
				CATEGORIE previousValue = this._CATEGORIE.Entity;
				if (((previousValue != value) 
							|| (this._CATEGORIE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CATEGORIE.Entity = null;
						previousValue.PRODOTTIs.Remove(this);
					}
					this._CATEGORIE.Entity = value;
					if ((value != null))
					{
						value.PRODOTTIs.Add(this);
						this._nomeCategoria = value.nome;
					}
					else
					{
						this._nomeCategoria = default(string);
					}
					this.SendPropertyChanged("CATEGORIE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEZIONI_PRODOTTI", Storage="_SEZIONI", ThisKey="nomeSezione", OtherKey="nome", IsForeignKey=true)]
		public SEZIONI SEZIONI
		{
			get
			{
				return this._SEZIONI.Entity;
			}
			set
			{
				SEZIONI previousValue = this._SEZIONI.Entity;
				if (((previousValue != value) 
							|| (this._SEZIONI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SEZIONI.Entity = null;
						previousValue.PRODOTTIs.Remove(this);
					}
					this._SEZIONI.Entity = value;
					if ((value != null))
					{
						value.PRODOTTIs.Add(this);
						this._nomeSezione = value.nome;
					}
					else
					{
						this._nomeSezione = default(string);
					}
					this.SendPropertyChanged("SEZIONI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_PRODOTTI", Storage="_UTENTI", ThisKey="emailUtenteAcquisto", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI
		{
			get
			{
				return this._UTENTI.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI.Entity = null;
						previousValue.PRODOTTIs.Remove(this);
					}
					this._UTENTI.Entity = value;
					if ((value != null))
					{
						value.PRODOTTIs.Add(this);
						this._emailUtenteAcquisto = value.email;
					}
					else
					{
						this._emailUtenteAcquisto = default(string);
					}
					this.SendPropertyChanged("UTENTI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_PRODOTTI1", Storage="_UTENTI1", ThisKey="emailUtenteVendita", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI1
		{
			get
			{
				return this._UTENTI1.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI1.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI1.Entity = null;
						previousValue.PRODOTTIs1.Remove(this);
					}
					this._UTENTI1.Entity = value;
					if ((value != null))
					{
						value.PRODOTTIs1.Add(this);
						this._emailUtenteVendita = value.email;
					}
					else
					{
						this._emailUtenteVendita = default(string);
					}
					this.SendPropertyChanged("UTENTI1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POST")]
	public partial class POST : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _codicePost;
		
		private string _titolo;
		
		private string _descrizione;
		
		private System.DateTime _data;
		
		private System.TimeSpan _time;
		
		private string _emailUtente;
		
		private string _nomeSezione;
		
		private EntitySet<COMMENTI> _COMMENTIs;
		
		private EntityRef<SEZIONI> _SEZIONI;
		
		private EntityRef<UTENTI> _UTENTI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodicePostChanging(long value);
    partial void OncodicePostChanged();
    partial void OntitoloChanging(string value);
    partial void OntitoloChanged();
    partial void OndescrizioneChanging(string value);
    partial void OndescrizioneChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    partial void OntimeChanging(System.TimeSpan value);
    partial void OntimeChanged();
    partial void OnemailUtenteChanging(string value);
    partial void OnemailUtenteChanged();
    partial void OnnomeSezioneChanging(string value);
    partial void OnnomeSezioneChanged();
    #endregion
		
		public POST()
		{
			this._COMMENTIs = new EntitySet<COMMENTI>(new Action<COMMENTI>(this.attach_COMMENTIs), new Action<COMMENTI>(this.detach_COMMENTIs));
			this._SEZIONI = default(EntityRef<SEZIONI>);
			this._UTENTI = default(EntityRef<UTENTI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codicePost", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long codicePost
		{
			get
			{
				return this._codicePost;
			}
			set
			{
				if ((this._codicePost != value))
				{
					this.OncodicePostChanging(value);
					this.SendPropertyChanging();
					this._codicePost = value;
					this.SendPropertyChanged("codicePost");
					this.OncodicePostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titolo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string titolo
		{
			get
			{
				return this._titolo;
			}
			set
			{
				if ((this._titolo != value))
				{
					this.OntitoloChanging(value);
					this.SendPropertyChanging();
					this._titolo = value;
					this.SendPropertyChanged("titolo");
					this.OntitoloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrizione", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				if ((this._descrizione != value))
				{
					this.OndescrizioneChanging(value);
					this.SendPropertyChanging();
					this._descrizione = value;
					this.SendPropertyChanged("descrizione");
					this.OndescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="Date NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time NOT NULL")]
		public System.TimeSpan time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailUtente", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string emailUtente
		{
			get
			{
				return this._emailUtente;
			}
			set
			{
				if ((this._emailUtente != value))
				{
					if (this._UTENTI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailUtenteChanging(value);
					this.SendPropertyChanging();
					this._emailUtente = value;
					this.SendPropertyChanged("emailUtente");
					this.OnemailUtenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeSezione", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nomeSezione
		{
			get
			{
				return this._nomeSezione;
			}
			set
			{
				if ((this._nomeSezione != value))
				{
					if (this._SEZIONI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnomeSezioneChanging(value);
					this.SendPropertyChanging();
					this._nomeSezione = value;
					this.SendPropertyChanged("nomeSezione");
					this.OnnomeSezioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="POST_COMMENTI", Storage="_COMMENTIs", ThisKey="codicePost", OtherKey="codicePost")]
		public EntitySet<COMMENTI> COMMENTIs
		{
			get
			{
				return this._COMMENTIs;
			}
			set
			{
				this._COMMENTIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEZIONI_POST", Storage="_SEZIONI", ThisKey="nomeSezione", OtherKey="nome", IsForeignKey=true)]
		public SEZIONI SEZIONI
		{
			get
			{
				return this._SEZIONI.Entity;
			}
			set
			{
				SEZIONI previousValue = this._SEZIONI.Entity;
				if (((previousValue != value) 
							|| (this._SEZIONI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SEZIONI.Entity = null;
						previousValue.POSTs.Remove(this);
					}
					this._SEZIONI.Entity = value;
					if ((value != null))
					{
						value.POSTs.Add(this);
						this._nomeSezione = value.nome;
					}
					else
					{
						this._nomeSezione = default(string);
					}
					this.SendPropertyChanged("SEZIONI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_POST", Storage="_UTENTI", ThisKey="emailUtente", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI
		{
			get
			{
				return this._UTENTI.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI.Entity = null;
						previousValue.POSTs.Remove(this);
					}
					this._UTENTI.Entity = value;
					if ((value != null))
					{
						value.POSTs.Add(this);
						this._emailUtente = value.email;
					}
					else
					{
						this._emailUtente = default(string);
					}
					this.SendPropertyChanged("UTENTI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_COMMENTIs(COMMENTI entity)
		{
			this.SendPropertyChanging();
			entity.POST = this;
		}
		
		private void detach_COMMENTIs(COMMENTI entity)
		{
			this.SendPropertyChanging();
			entity.POST = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMMENTI")]
	public partial class COMMENTI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _codiceCommento;
		
		private string _descrizione;
		
		private System.DateTime _data;
		
		private System.TimeSpan _time;
		
		private string _emailUtente;
		
		private long _codicePost;
		
		private EntityRef<POST> _POST;
		
		private EntityRef<UTENTI> _UTENTI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodiceCommentoChanging(long value);
    partial void OncodiceCommentoChanged();
    partial void OndescrizioneChanging(string value);
    partial void OndescrizioneChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    partial void OntimeChanging(System.TimeSpan value);
    partial void OntimeChanged();
    partial void OnemailUtenteChanging(string value);
    partial void OnemailUtenteChanged();
    partial void OncodicePostChanging(long value);
    partial void OncodicePostChanged();
    #endregion
		
		public COMMENTI()
		{
			this._POST = default(EntityRef<POST>);
			this._UTENTI = default(EntityRef<UTENTI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codiceCommento", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long codiceCommento
		{
			get
			{
				return this._codiceCommento;
			}
			set
			{
				if ((this._codiceCommento != value))
				{
					this.OncodiceCommentoChanging(value);
					this.SendPropertyChanging();
					this._codiceCommento = value;
					this.SendPropertyChanged("codiceCommento");
					this.OncodiceCommentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descrizione", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				if ((this._descrizione != value))
				{
					this.OndescrizioneChanging(value);
					this.SendPropertyChanging();
					this._descrizione = value;
					this.SendPropertyChanged("descrizione");
					this.OndescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="Date NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time NOT NULL")]
		public System.TimeSpan time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailUtente", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string emailUtente
		{
			get
			{
				return this._emailUtente;
			}
			set
			{
				if ((this._emailUtente != value))
				{
					if (this._UTENTI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnemailUtenteChanging(value);
					this.SendPropertyChanging();
					this._emailUtente = value;
					this.SendPropertyChanged("emailUtente");
					this.OnemailUtenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codicePost", DbType="BigInt NOT NULL")]
		public long codicePost
		{
			get
			{
				return this._codicePost;
			}
			set
			{
				if ((this._codicePost != value))
				{
					if (this._POST.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodicePostChanging(value);
					this.SendPropertyChanging();
					this._codicePost = value;
					this.SendPropertyChanged("codicePost");
					this.OncodicePostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="POST_COMMENTI", Storage="_POST", ThisKey="codicePost", OtherKey="codicePost", IsForeignKey=true)]
		public POST POST
		{
			get
			{
				return this._POST.Entity;
			}
			set
			{
				POST previousValue = this._POST.Entity;
				if (((previousValue != value) 
							|| (this._POST.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._POST.Entity = null;
						previousValue.COMMENTIs.Remove(this);
					}
					this._POST.Entity = value;
					if ((value != null))
					{
						value.COMMENTIs.Add(this);
						this._codicePost = value.codicePost;
					}
					else
					{
						this._codicePost = default(long);
					}
					this.SendPropertyChanged("POST");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UTENTI_COMMENTI", Storage="_UTENTI", ThisKey="emailUtente", OtherKey="email", IsForeignKey=true)]
		public UTENTI UTENTI
		{
			get
			{
				return this._UTENTI.Entity;
			}
			set
			{
				UTENTI previousValue = this._UTENTI.Entity;
				if (((previousValue != value) 
							|| (this._UTENTI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UTENTI.Entity = null;
						previousValue.COMMENTIs.Remove(this);
					}
					this._UTENTI.Entity = value;
					if ((value != null))
					{
						value.COMMENTIs.Add(this);
						this._emailUtente = value.email;
					}
					else
					{
						this._emailUtente = default(string);
					}
					this.SendPropertyChanged("UTENTI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
